RegisterNetEvent("menuweashop:melee")
AddEventHandler("menuweashop:melee", function()
    VMenu.AddFunc(22, "Retour", "vmenu:openMenu", {22}, "Retourner au menu principal")
	VMenu.AddFunc(22, "Couteau", "giveWeapon", {WEAPON_Knife, 100, -400}, "Coût: 400$")
	VMenu.AddFunc(22, "Batte de baseball", "giveWeapon", {WEAPON_Bat, 100, -750}, "Coût: 750$")
end)

RegisterNetEvent('giveWeapon')
AddEventHandler('giveWeapon', function(name, delay, price)
	Citizen.CreateThread(function()
		local weapon = GetHashKey(name)
        Wait(delay)
        local hash = GetHashKey(name)
        GiveWeaponToPed(GetPlayerPed(-1), weapon, 1000, 0, false)
		TriggerServerEvent("mine:addmoney",(price))
    end)
end)